# Hugo Blox GitHub Action to convert Bibtex publications to Markdown-based webpages
name: Import Publications From Bibtex

# Require permission to create a PR
permissions:
  contents: write
  issues: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated in the root folder
on:
  push:
    branches: ['main']
    paths: ['*.bib']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0
          pip install bibtexparser pyyaml citeproc-py pybtex
      - name: Import Journal Articles
        # Check if journal articles bib file exists
        if: ${{ hashFiles('journal_articles.bib') != '' }}
        run: academic import journal_articles.bib content/publication/ --compact
      - name: Import Preprints
        # Check if preprints bib file exists
        if: ${{ hashFiles('preprints.bib') != '' }}
        run: academic import preprints.bib content/publication/ --compact
      - name: Import Conference Papers
        # Check if conference papers bib file exists
        if: ${{ hashFiles('conference_papers.bib') != '' }}
        run: academic import conference_papers.bib content/publication/ --compact
      - name: Import Talks
        # Check if talks bib file exists
        if: ${{ hashFiles('talks.bib') != '' }}
        run: academic import talks.bib content/publication/ --compact
      - name: Import Publications (fallback for single file)
        # Check if single publications.bib file exists
        if: ${{ hashFiles('publications.bib') != '' }}
        run: academic import publications.bib content/publication/ --compact
      - name: Copy CSL file and enhance publication metadata
        run: |
          # Copy the CSL file to the working directory
          if [ -f "apa-cv.csl" ]; then
            cp apa-cv.csl .
            echo "CSL file copied successfully"
          else
            echo "Warning: CSL file not found, will use fallback formatting"
          fi
          
          # Copy the enhanced publications script
          if [ -f "enhance_publications.py" ]; then
            cp enhance_publications.py .
            echo "Enhanced publications script copied successfully"
          else
            echo "Error: Enhanced publications script not found"
            exit 1
          fi
          
          python enhance_publications.py
      - name: Create Pull Request
        # Set ID for `Check outputs` stage
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'content: import publications from Bibtex with APA-7 CSL formatting'
          title: Hugo Blox Builder - Import latest publications with APA-7 formatting
          body: |
            Import the latest publications from BibTeX files to `content/publication/` with enhanced metadata including:
            - APA-7 style formatting using CSL (Citation Style Language)
            - Properly formatted publication fields with volume, issue, and pages
            - Author highlighting for the site owner
            - DOI and URL links when available
            
            将最新的出版物从BibTeX文件导入到`content/publication/`，使用APA-7格式。
            [View Documentation](https://github.com/GetRD/academic-file-converter)
          base: main
          labels: automated-pr, content
          branch: hugoblox-import-publications
          delete-branch: true
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
